### ISSUE TITLE
SSH Command: Auth fail when connecting to shell with username / pw

### ISSUE THREAD

**Issue by ceazy79** [yciabaud/jmeter-ssh-sampler#19]
Hi,

I'm trying to connect to a remote machine using username/password. I tried creating a very simple test plan with just the "SSH command" sampler and a "View results tree". I entered the credentials in the sampler config but get an "Auth fail" error.

Plugin version: 1.1.1
JMeter 3.2 and 4.0

This is the exception from the log view:
`018-09-12 16:21:46,052 ERROR o.a.j.p.s.s.AbstractSSHSampler: SSH connexion error
com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512) ~[jsch-0.1.50.jar:?]
	at org.apache.jmeter.protocol.ssh.sampler.AbstractSSHSampler.connect(AbstractSSHSampler.java:72) [ApacheJMeter_ssh-1.1.1-SNAPSHOT.jar:?]
	at org.apache.jmeter.protocol.ssh.sampler.SSHCommandSampler.sample(SSHCommandSampler.java:64) [ApacheJMeter_ssh-1.1.1-SNAPSHOT.jar:?]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:490) [ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:416) [ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250) [ApacheJMeter_core.jar:4.0 r1823414]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
2018-09-12 16:21:46,052 ERROR o.a.j.p.s.s.SSHCommandSampler: Failed to connect to server with credentials [correct username]@[correct ip]:22 pw=[correct pw]
`
The username, password, ip and port that are printed in the log view are correct and working connecting from a shell.

In the following branch I created a fix so that the login is now working:
https://github.com/ceazy79/jmeter-ssh-sampler/tree/bugfix/auth-fail-interactive-login-fix

BR
Chris

**Comment by yciabaud** [comment]
Sounds nice! Would you mind making a PR to make it available for all?

**Comment by yciabaud** [comment]
Thanks!

**Comment by yciabaud** [comment]
You got it!
