### ISSUE TITLE
jmeter.protocol.ssh.sampler.AbstractSSHSampler: SSH connexion error com.jcraft.jsch.JSchException: java.net.UnknownHostException

### ISSUE THREAD

**Issue by npocmaka** [yciabaud/jmeter-ssh-sampler#6]
Here's the exception I receive:

```
2016/10/06 10:57:15 ERROR - jmeter.protocol.ssh.sampler.AbstractSSHSampler: SSH connexion error com.jcraft.jsch.JSchException: java.net.UnknownHostException: XXXX
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at org.apache.jmeter.protocol.ssh.sampler.AbstractSSHSampler.connect(AbstractSSHSampler.java:72)
	at org.apache.jmeter.protocol.ssh.sampler.SSHCommandSampler.sample(SSHCommandSampler.java:64)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:431)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:258)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: XXXX
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at com.jcraft.jsch.Util$1.run(Util.java:362)
	... 1 more
```

I had similar error using directly **jsch** but with **config.put("StrictHostKeyChecking", "no");**  I have no problems. Haven't tried to fork your plugin and check without _StrictHostKeyChecking_ yet (or with with passing **known_hosts** file) , but this is the next thing I'll try

**Comment by yciabaud** [comment]
Well, disabling the `StrictHostKeyChecking` disable many security check and we should not use it.

Maybe this host is not correctly configured (keys / hostname)... Can you connect to it using SSH client?

**Comment by npocmaka** [comment]
Yes I can - this is the reason I've tried with jsch . May be turning off host checking could be optional , but this will cause more development...

**Comment by yciabaud** [comment]
Have you tried using the server IP address? Just to check if this is a host resolution problem or not.

**Comment by npocmaka** [comment]
hmm.. Yes it works with IP (didn't come to me to try like this) . But I'm not sure if the IP address will be the same each time.Anyway this is a good workaround.Thanks.

**Comment by yciabaud** [comment]
This is telling us Java cannot resolve your hostname, this may be related to security policies or other system configuration.

Since you are telling that `StrictHostKeyChecking` is working, it should be related to the SSH keys stored on the system user.

Did you tried using ssh client with the same system / user as jmeter?

**Comment by npocmaka** [comment]
yes. I can connect with ssh client, winscp and with an example java snipped using directly jsch library.Still I have an issue only with the jmeter plugin. Jmeter is using the same jdk as the snippet. Anyway I can get the IP through jmeter so it usable now.

**Comment by yciabaud** [comment]
I would like to figure out what is going on but I dont know how.

I close the issue, please tell me if you find another clue ;)
